# Generated by Django 5.1.1 on 2024-11-04 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='street_address',
            new_name='addressDetail',
        ),
        migrations.RenameField(
            model_name='address',
            old_name='city',
            new_name='province',
        ),
    ]
